Added ability to upgrade all plugins at once, prevent updating plugins twice

diff --git a/makeXcodePluginsWork b/makeXcodePluginsWork
--- a/makeXcodePluginsWork
+++ b/makeXcodePluginsWork
@@ -9,21 +9,17 @@ tmpRepoPath="/tmp/unsign-updatePlugins"
 bold=$(tput bold)
 normal=$(tput sgr0)
 
-function print {
-	echo "${bold}$1${normal}"
-}
-
 if pgrep "Xcode" > /dev/null
 then
-    print "${bold}Xcode is Running, please quit first${normal}"
+    printf "${bold}Xcode is Running, please quit first${normal}"
     exit 1
 fi
 
 while true
 do
 
-	declare -a mainOptTests=("unsign" "restoreUnsigned" "restoreSigned" "update" "quit")
-	declare -a mainOpts=("Unsign Xcode" "Restore unsigned Xcode" "Restore signed Xcode" "Update plugins" "Quit")
+	declare -a mainOptTests=("unsign" "restoreUnsigned" "restoreSigned" "update" "updateAll" "quit")
+	declare -a mainOpts=("Unsign Xcode" "Restore unsigned Xcode" "Restore signed Xcode" "Update specific plugins" "Update all plugins" "Quit")
 
 	if [ -f "$binaryPath.unsigned" ]; then
 		unset mainOptTests[2]
@@ -43,59 +39,72 @@ do
 	mainOptTests=( "${mainOptTests[@]}" )
 	mainOpts=( "${mainOpts[@]}" )
 
-	echo "${bold}"
-	PS3="Which do you want to do?: ${normal}"
+	printf "\n${bold}"
+	PS3="${bold}Which do you want to do?: ${normal}"
 	select opt in "${mainOpts[@]}" ; do 
-		echo "${normal}"
+		printf "${normal}"
 		testRes=${mainOptTests[REPLY-1]}
 		case $testRes in
 			"unsign" )
-				print "This will unsign Xcode. This can be reversed using this script. To continue, type 'unsign'. To cancel, hit return."
+				printf "This will unsign Xcode. This can be reversed using this script. To continue, type 'unsign'. To cancel, hit return."
 				read typed
 				if [ "$typed" == "unsign" ] ; then
 					rm -rf "$tmpRepoPath"
 					mkdir "$tmpRepoPath"
 					cd $tmpRepoPath
-					echo "Cloning unsign repository"
+					printf "Cloning unsign repository"
 					git clone git@github.com:steakknife/unsign.git
 					cd unsign
 					make
 					
-					print "Unsigning (admin permissions required)"
+					printf "Unsigning (admin permissions required)"
 					sudo ./unsign "$binaryPath"
 					status=$?
 					if [ $status -eq 0 ]; then
 						sudo mv "$binaryPath" "$binaryPath.signed"
 						sudo mv "$binaryPath.unsigned" "$binaryPath"
-						print "Done!"
+						printf "Done!"
 					else
-						print "Failed."
+						printf "Failed."
 					fi
 					rm -rf "$tmpRepoPath"
 				else
-					print "Didn't type unsign."
+					printf "Didn't type unsign."
 				fi
 				break
 				;;
 			"restoreUnsigned" )
 				sudo mv "$binaryPath" "$binaryPath.signed"
 				sudo mv "$binaryPath.unsigned" "$binaryPath"
-				print "Restored unsigned binary"
+				printf "Restored unsigned binary"
 				break
 				;;
 			"restoreSigned" )
 				sudo mv "$binaryPath" "$binaryPath.unsigned"
 				sudo mv "$binaryPath.signed" "$binaryPath"
-				print "Restored signed binary"
+				printf "Restored signed binary"
 				break
 				;;
-			"update" )
+			"update" | "updateAll" )
 				UUID=$(defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID)
+
+				function containsElement {
+					local e
+					for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
+					return 1
+				}
+
+				found=0
 
 				function findPlugins {
 					plugins=()
 					while read -d '' -r; do
-					    plugins+=( "$REPLY" )
+						((found++))
+						existingUUIDs=($(defaults read "$REPLY/Contents/Info" DVTPlugInCompatibilityUUIDs | sed "s/[,()\"]*//g"))
+						containsElement "$UUID" "${existingUUIDs[@]}"
+						if [ $? -eq 1 ]; then
+						    plugins+=( "$REPLY" )
+					   	fi
 					done < <(find "$1" -name "*.xcplugin" -maxdepth 1 -print0 2>/dev/null)
 				}
 
@@ -104,24 +113,52 @@ do
 				findPlugins "$altPluginsDir"
 				options=( "${options[@]}" "${plugins[@]}" )
 
+				printf "\n"
 
-				echo "${bold}"
-				PS3="Please select a plugin to update: ${normal}"
-				select opt in "${options[@]}" "Back" "Quit" ; do 
-					if (( REPLY == 1 + ${#options[@]} )) ; then
-						break
+				if [ ${#options[@]} -eq 0 ]; then
+					printf "No plugins need upgrading! $found plugins found already have latest UUID."
+					break
+				else
+					((upgraded=$found-${#options[@]}))
+					if [ $upgraded -gt 0 ]; then
+						printf "$upgraded plugins already have latest UUID.\n"
+					fi
+				fi
 
-					elif (( REPLY == 2 + ${#options[@]} )) ; then
-						exit
+				function upgradePlugin {
+					defaults write "$1/Contents/Info"  DVTPlugInCompatibilityUUIDs -array-add $UUID
+			        printf "Upgraded $1"
+				}
 
-				    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
-				    	defaults write "$opt/Contents/Info"  DVTPlugInCompatibilityUUIDs -array-add $UUID
-				        print "Upgraded $opt"
+				if [ $testRes == "update" ]; then
+					printf "\n${bold}"
+					upgraded=()
+					PS3="${bold}Please select a plugin to update: ${normal}"
+					select opt in "${options[@]}" "Back" "Quit" ; do 
+						if (( REPLY == 1 + ${#options[@]} )) ; then
+							break
 
-				    else
-				        print "Invalid option. Try another one."
-				    fi
-				done
+						elif (( REPLY == 2 + ${#options[@]} )) ; then
+							exit
+
+					    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
+					    	containsElement "$opt" "${upgraded[@]}"
+					    	if [ $? -eq 1 ]; then
+						    	upgradePlugin "$opt"
+						    	upgraded+="$opt"
+						    else
+						    	printf "Already upgraded this plugin"
+						    fi
+					    else
+					        printf "Invalid option. Try another one."
+					    fi
+					    printf "\n"
+					done
+				else
+					for i in "${options[@]}"; do
+			            upgradePlugin "$i"
+			        done
+				fi
 				break
 				;;
 			"quit" )
